### ISSUE TITLE
get_checks() error in e_bayesscoring

### ISSUE THREAD

**Issue by annaymj** [markhwhiteii/bwstools#40]
![image](https://user-images.githubusercontent.com/3307857/97264013-54a34a00-17e1-11eb-8e6e-6b8dcca9c59f.png)
Hi,
  The newly added get_checks() function is causing the following error. Please advice the way to work around it. 

Error in get_checks(data, id, block, item, choice): Each pairwise comparison between items must occur the same amount
  of times for each id.
Traceback:

1. bwsTools::e_bayescoring(dat1, "pid", "block", "label", "resp")
2. get_checks(data, id, block, item, choice)
3. stop("Each pairwise comparison between items must occur the same amount\n  of times for each id.")

Thanks!

**Comment by annaymj** [comment]
I copied your e_bayesscoring function and commented out get_checks(), it worked fine.

**Comment by markhwhiteii** [comment]
The empirical Bayes method (and the analytical estimation of the multinomial logit model that it's derived from) assumes that data come from a balanced incomplete block design (BIBD). (See the paper here: https://osf.io/xftvq/).

What this error is saying is that your data do not come from a BIBD: Each pairwise comparison between items does not occur the same amount of times.

I'm currently working on a paper to see how robust these estimations are to violating a BIBD, but for now I would suggest using the eloscoring function if your data do not come from a balanced design.
